# Generated by Django 5.1.5 on 2025-02-28 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_hub'),
        ('hubs', '0002_alter_hub_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='hubs.hub'),
        ),
    ]
