# Generated by Django 5.1.8 on 2025-04-08 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notification_usersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='service_type',
            field=models.CharField(choices=[('events', 'Events'), ('p2p', 'P2P'), ('freelance', 'Freelance'), ('blogs', 'Blogs'), ('communities', 'Communities'), ('all', 'All')], default='all', help_text='The type of service this category belongs to.', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscribed_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
