# Generated by Django 5.1.8 on 2025-04-04 17:32

import p2p.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='p2p/default.png', upload_to=p2p.models.rename),
        ),
    ]
