# Generated by Django 5.1.7 on 2025-03-30 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_post_updated_at'),
        ('utils', '0008_alter_category_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(limit_choices_to={'service_type': 'blogs'}, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='utils.category'),
        ),
    ]
