# Generated by Django 5.1.7 on 2025-04-01 01:30

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(default='blogs/default.png', upload_to=blogs.models.rename),
        ),
    ]
