# Generated by Django 5.1.7 on 2025-03-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_about_updated_at_alter_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-position']},
        ),
        migrations.AddField(
            model_name='about',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
