# Generated by Django 5.1.7 on 2025-03-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_alter_about_options_about_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='header',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='about',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
