# Generated by Django 5.1.7 on 2025-03-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='icon',
            field=models.CharField(max_length=100),
        ),
    ]
