# Generated by Django 5.1.7 on 2025-03-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_alter_about_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='service_type',
            field=models.CharField(choices=[('events', 'Events'), ('p2p', 'P2P'), ('freelance', 'Freelance'), ('blogs', 'Blogs'), ('communities', 'Communities')], help_text='The type of service this category belongs to.', max_length=20),
        ),
    ]
