# Generated by Django 5.1.7 on 2025-03-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_description_alter_event_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Content for description meta tag', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma delimited set of SEO keywords for meta tag', max_length=255, null=True),
        ),
    ]
