# Generated by Django 5.1.7 on 2025-03-22 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-updated_at']},
        ),
    ]
