# Generated by Django 5.1.7 on 2025-03-25 00:23

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(default='events/default.jpg', upload_to=events.models.rename),
        ),
    ]
