# Generated by Django 5.1.7 on 2025-03-29 23:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_capacity'),
        ('hubs', '0004_alter_hub_updated_at'),
        ('utils', '0008_alter_category_service_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_start_t_c2d277_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_end_tim_a200ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_status_5709b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_name_d5901c_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_venue_1f7c5d_idx',
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_time', 'end_time', 'status', 'name', 'venue'], name='events_even_start_t_85162b_idx'),
        ),
    ]
