# Generated by Django 5.1.5 on 2025-02-28 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0002_alter_hub_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administered_hub', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hub',
            name='location',
            field=models.CharField(default='Owerri, Imo state.', max_length=100),
            preserve_default=False,
        ),
    ]
